### ISSUE TITLE
Frontend / REST integration

### ISSUE THREAD

**Issue by Volskaar** [Norace2002/SWEN3#21]
Frontend needs to make calls to REST server
at least:
- GET /documents
- GET /documents/{id}
- POST /documents

**Comment by Norace2002** [comment]
- Added event handler that triggers when page pops up -  to load documents from database
- Included new calls to restserver (/documents , /documents/{id}/metadata, /documents (POST))
- Implemented basic drag and drop functionality
- Updated previous upload per click functionality
- Added placeholders for the missing form - interface (easily replaceable)
- Merged dev into main (now up to date)
